"""Write docs/COMMANDS.md from the command declarations (the single source of truth).

    python tools/gen_docs.py

A test fails when the committed file is out of date, so the reference never drifts."""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "COMMANDS.md")

GROUP_TITLES = {
    "observe": "Observe - see what is on screen",
    "act": "Act - through accessibility (no mouse, verified)",
    "mouse": "Mouse - real pointer, guarded",
    "keyboard": "Keyboard and clipboard",
    "windows": "Windows and apps",
    "vision": "Vision - pixels and OCR, for apps without a tree",
    "office": "Office - Excel and Word through their object model",
    "system": "System - shell, files, processes (off by default)",
    "workflow": "Workflow - batch, replay, setup",
}


def _load():
    if "uiautomation" not in sys.modules:           # documentation needs no Windows
        sys.path.insert(0, os.path.join(ROOT, "tests"))
        import fake_uia
        sys.modules["uiautomation"] = fake_uia
    sys.path.insert(0, ROOT)
    from wadlib import cli  # noqa: F401
    from wadlib.registry import COMMANDS, GROUPS
    return COMMANDS, GROUPS


def usage(c):
    parts = [f"wad {c.name}"]
    for a in c.args:
        if a.positional:
            parts.append(f"[{a.name.upper()}]" if a.optional else a.name.upper())
    if any(not a.positional for a in c.args):
        parts.append("[options]")
    return " ".join(parts)


def render():
    commands, groups = _load()
    out = ["# wad command reference", "",
           "Generated by `python tools/gen_docs.py` from the command declarations - the same",
           "ones that build the command line and the MCP tools. Every command also takes",
           "`--json`. Targets are a ref from the last snapshot (`e12`) or a selector",
           "(`role=Button name=Save`, see [SELECTORS.md](SELECTORS.md)).", ""]
    out.append("| Group | Commands |")
    out.append("|---|---|")
    for g in groups:
        names = [c.name for c in commands.values() if c.group == g]
        if names:
            out.append(f"| {g} | " + ", ".join(f"[`{n}`](#{n})" for n in names) + " |")
    for g in groups:
        cs = [c for c in commands.values() if c.group == g]
        if not cs:
            continue
        out += ["", f"## {GROUP_TITLES[g]}"]
        for c in cs:
            out += ["", f"### {c.name}", "", c.help[0].upper() + c.help[1:] + ".", "",
                    f"```\n{usage(c)}\n```"]
            if c.args:
                out += ["", "| Argument | Type | Default | Meaning |", "|---|---|---|---|"]
                for a in c.args:
                    name = a.name.upper() if a.positional else f"`--{a.name}`" + (
                        f" `{a.short}`" if a.short else "")
                    typ = {str: "text", int: "integer", float: "number", bool: "flag"}[a.type]
                    if a.choices:
                        typ = " \\| ".join(a.choices)
                    default = "" if a.default in (None, False) else f"`{a.default}`"
                    need = " (required)" if a.is_required and not a.positional else ""
                    out.append(f"| {name} | {typ} | {default} | {a.help}{need} |")
            flags = []
            if c.readonly:
                flags.append("read-only")
            if not c.mcp:
                flags.append("command line only")
            if c.image:
                flags.append("MCP result includes the image")
            if flags:
                out += ["", "_" + ", ".join(flags) + "_"]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    text = render()
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {OUT}")
